nodeLinker: node-modules

# Dependency lifecycle scripts are not required by this service and are disabled
# to prevent package install scripts executing in CI or local development.
enableScripts: false

yarnPath: .yarn/releases/yarn-4.7.0.cjs
