version: '2'

services:
  xui-icp:
    image: hmctsprod.azurecr.io/xui/icp-api:aat-a808eaa1
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - 8080:8080
  redis:
    image: redis
    ports:
      - 6379:6379
