redis:
  host: REDIS_HOST
  port: REDIS_PORT
  password: REDIS_PASSWORD
  useTLS: REDIS_USE_TLS

pact:
  pactBrokerUrl: PACT_BROKER_URL

appInsights:
  instrumentationKey: APPINSIGHTS_INSTRUMENTATIONKEY

idam:
  url: IDAM_API_BASE_URL

rateLimit:
  time: RATE_LIMIT_TIME
  max: RATE_LIMITE_MAX

icp:
  wsUrl: ICP_WS_URL
  allowedOrigin: ICP_ALLOWED_ORIGIN
